#pragma once

#include "Module/Modules/FogColor.h"
#include "Module/Modules/FullBright.h"
#include "Module/Modules/ItemPhysics.h"
#include "Module/Modules/JavaFov.h"
#include "Module/Modules/MotionBlur.h"
#include "Module/Modules/NoDynamicFov.h"
#include "Module/Modules/NoHurtCam.h"
#include "Module/Modules/SelfNameTag.h"
#include "Module/Modules/Skybox.h"
#include "Module/Modules/Zoom.h"

#include "Module/Modules/ArrayList.h"
#include "Module/Modules/Notifications.h"
#include "Module/Modules/Watermark.h"

#include "Module/Modules/Aliases.h"
#include "Module/Modules/AutoSprint.h"
#include "Module/Modules/DiagonalSprint.h"
#include "Module/Modules/ItemDelayFix.h"
#include "Module/Modules/JavaHotkeys.h"
#include "Module/Modules/NoCamReset.h"
#include "Module/Modules/QuickSlots.h"
#include "Module/Modules/SensMultiplier.h"

#include "Module/Modules/ClickGuiModule.h"
#include "Module/Modules/Overlay.h"
#include "Module/Modules/NoVSync.h"
#include "Module/Modules/PackSwitcher.h"
